apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cockroachdb-operator
rules:
# Allow creating CRDs
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "create", "update", "watch"]

# Allow all actions on Cockroachdb Chart
- apiGroups: ["helm.operator-sdk"]
  resources: ["cockroachdbs", "cockroachdbs/status"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

# Allow actions on Prometheus Operator Service Monitor CRD
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions on Kubernetes Endpoints
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

# Allow actions on Kubernetes Cluster Role and Cluster Role Binding
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

# Allow listing Namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]

- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "watch"]
